---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v2
        with:
          configpath: .github/workflows/.luarc.json
          path: lua
